DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyNjkwNDYsInVzZXJJZCI6MX0.NL_NpExmkWIBJ9XqBtrnDfsgkybXEXfZoC_oCmC2LNI