POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyNjY2NjIsInVzZXJJZCI6MX0.gtWkjITflanWdL8rj1OZPnOZOI6E038-qPbs57W2JM8 

{
  "name": "Test event",
  "description": "Test description",
  "location": "Test location",
  "datetime": "2025-02-01T15:30:00.000Z"
}