POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUxMjY1MDkyLCJ1c2VySWQiOjJ9.Hf1ED5CAqyEK-ZCBF_cQtbSQvLzl22Nht4RBVSCEgmI

{
  "name": "Test event",
  "description": "Test description",
  "location": "Test location",
  "datetime": "2025-02-01T15:30:00.000Z"
}