DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEyNjczNjMsInVzZXJJZCI6MX0.pxwmanUgvUz4fupQb4GqDcSMZnit42VeuACnVKxCVok