PUT http://localhost:8080/events/2
Content-Type: application/json

{
  "name": "Test event 2 Updated",
  "description": "Test description 2 Updated",
  "location": "Test location 2 Updated",
  "datetime": "2025-02-01T15:30:00.000Z"
}
